package compute


func ServiceListResponseBody() string {
	return `
{"services": [{"binary": "nova-scheduler", "host": "controller", "id": 1, "zone": "internal", "status": "enabled", "state": "up", "updated_at": "2019-07-23T10:09:15.000000", "disabled_reason": null}, {"binary": "nova-conductor", "host": "controller", "id": 2, "zone": "internal", "status": "enabled", "state": "up", "updated_at": "2019-07-23T10:09:16.000000", "disabled_reason": null}, {"binary": "nova-consoleauth", "host": "controller", "id": 5, "zone": "internal", "status": "enabled", "state": "up", "updated_at": "2019-07-23T10:09:17.000000", "disabled_reason": null}, {"binary": "nova-compute", "host": "compute01", "id": 6, "zone": "nova", "status": "enabled", "state": "down", "updated_at": "2019-07-22T08:28:08.000000", "disabled_reason": null}, {"binary": "nova-compute", "host": "compute02", "id": 7, "zone": "nova", "status": "enabled", "state": "down", "updated_at": "2019-07-22T08:28:08.000000", "disabled_reason": null}]}
`
}
func HypervisorsListResponseBody() string {
	return `
{"hypervisors": [{"id": "b61ce119-0429-4035-bf4a-5349cdd4cc70", "hypervisor_hostname": "compute01", "state": "down", "status": "enabled", "vcpus": 6, "memory_mb": 7976, "local_gb": 410, "vcpus_used": 0, "memory_mb_used": 512, "local_gb_used": 0, "hypervisor_type": "QEMU", "hypervisor_version": 3001000, "free_ram_mb": 7464, "free_disk_gb": 410, "current_workload": 0, "running_vms": 0, "disk_available_least": 395, "host_ip": "192.168.28.52", "service": {"id": "2ee7095c-8540-4cc0-8755-885f99b8715f", "host": "compute01", "disabled_reason": null}, "cpu_info": {"arch": "x86_64", "model": "Skylake-Server-IBRS", "vendor": "Intel", "topology": {"cells": 1, "sockets": 6, "cores": 1, "threads": 1}, "features": ["tsc", "avx", "f16c", "clflush", "msr", "sep", "lm", "pae", "pse36", "avx512vl", "syscall", "hle", "lahf_lm", "avx2", "rdtscp", "xgetbv1", "pcid", "tsc-deadline", "avx512cd", "fsgsbase", "cx8", "ssse3", "de", "fma", "fxsr", "spec-ctrl", "pclmuldq", "pge", "sse", "fpu", "avx512bw", "adx", "osxsave", "arat", "xsavec", "mtrr", "nx", "rdseed", "aes", "pse", "rdrand", "sse2", "xsave", "3dnowprefetch", "invpcid", "movbe", "popcnt", "sse4.2", "mca", "mce", "smap", "sse4.1", "hypervisor", "cx16", "x2apic", "abm", "pdpe1gb", "avx512f", "erms", "cmov", "clwb", "pat", "vme", "apic", "pni", "xsaveopt", "bmi1", "rtm", "bmi2", "avx512dq", "mpx", "mmx", "smep"]}}, {"id": "730a3871-c05f-4da4-b31a-76d37cd00a5f", "hypervisor_hostname": "compute02", "state": "down", "status": "enabled", "vcpus": 8, "memory_mb": 7975, "local_gb": 410, "vcpus_used": 0, "memory_mb_used": 512, "local_gb_used": 0, "hypervisor_type": "QEMU", "hypervisor_version": 3001000, "free_ram_mb": 7463, "free_disk_gb": 410, "current_workload": 0, "running_vms": 0, "disk_available_least": 395, "host_ip": "192.168.28.53", "service": {"id": "d05dfba7-efe6-4d21-8f4d-3719b92cf7b1", "host": "compute02", "disabled_reason": null}, "cpu_info": {"arch": "x86_64", "model": "Skylake-Server-IBRS", "vendor": "Intel", "topology": {"cells": 1, "sockets": 8, "cores": 1, "threads": 1}, "features": ["sse", "rdtscp", "fpu", "xsave", "popcnt", "abm", "apic", "hypervisor", "pse36", "avx512dq", "pdpe1gb", "pge", "lahf_lm", "spec-ctrl", "adx", "movbe", "clwb", "tsc-deadline", "avx512bw", "mca", "erms", "fxsr", "nx", "syscall", "avx", "sep", "pse", "sse4.2", "xsavec", "cx16", "invpcid", "lm", "xsaveopt", "de", "msr", "rdseed", "clflush", "xgetbv1", "3dnowprefetch", "avx2", "bmi2", "avx512cd", "mce", "pae", "cx8", "rdrand", "aes", "tsc", "sse2", "x2apic", "rtm", "fma", "pclmuldq", "pni", "cmov", "pat", "fsgsbase", "ssse3", "bmi1", "avx512vl", "mpx", "osxsave", "mtrr", "pcid", "hle", "arat", "sse4.1", "avx512f", "vme", "smep", "f16c", "smap", "mmx"]}}]}
`
}
func QuotasListResponseBody() string {
	return `
{"quota_set": {"id": "33b03d1e28404ce68c8cf8c91506465b", "cores": {"limit": 20, "in_use": 0, "reserved": 0}, "fixed_ips": {"limit": -1, "in_use": 0, "reserved": 0}, "floating_ips": {"limit": 10, "in_use": 0, "reserved": 0}, "injected_file_content_bytes": {"limit": 10240, "in_use": 0, "reserved": 0}, "injected_file_path_bytes": {"limit": 255, "in_use": 0, "reserved": 0}, "injected_files": {"limit": 5, "in_use": 0, "reserved": 0}, "instances": {"limit": 10, "in_use": 0, "reserved": 0}, "key_pairs": {"limit": 100, "in_use": 0, "reserved": 0}, "metadata_items": {"limit": 128, "in_use": 0, "reserved": 0}, "ram": {"limit": 51200, "in_use": 0, "reserved": 0}, "security_group_rules": {"limit": 20, "in_use": 0, "reserved": 0}, "security_groups": {"limit": 10, "in_use": 1, "reserved": 0}, "server_group_members": {"limit": 10, "in_use": 0, "reserved": 0}, "server_groups": {"limit": 10, "in_use": 0, "reserved": 0}}}
`
}